### ISSUE TITLE
While updating RestSharp to v111.3, the MaxTimeout option is changed to Timeout

### ISSUE THREAD

**Issue by marcverkade** [CMS365-PTY-LTD/MetaSharp#10]
Breaking changes:

Client option MaxTimeout renamed to Timeout and changed type to Timespan for clarity. It doesn't configure the HttpClient timeout anymore. Instead, the same method is used for client and request level timeouts with cancellation tokens.
Request option Timeout changed type to Timespan for clarity.

using RestSharp;

namespace MetaSharp.Source
{
    public static class Helpers
    {
        public static RestClient GetRestClient()
        {
            var options = new RestClientOptions($"{Constants.GraphAPI.URL}/{Constants.GraphAPI.VERSION}")
            {
                // Old code: MaxTimeout = -1 - https://restsharp.dev/docs/changelog/;
                Timeout = TimeSpan.FromMilliseconds(-1),
            };
            return new RestClient(options);
        }
    }
}

**Comment by shafaqat-ali-cms365** [comment]
Thank you for repotting, I have fixed and pushed a new version.
